"""changed  website col to website_link col after looking at forms.py

Revision ID: 5c3bc8d6d0ab
Revises: 9979593c7025
Create Date: 2022-05-27 21:20:12.433262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c3bc8d6d0ab'
down_revision = '9979593c7025'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('website_link', sa.String(length=120), nullable=True))
    op.drop_constraint('Artist_website_key', 'Artist', type_='unique')
    op.create_unique_constraint(None, 'Artist', ['website_link'])
    op.drop_column('Artist', 'website')
    op.add_column('Venue', sa.Column('website_link', sa.String(length=120), nullable=False))
    op.drop_constraint('Venue_website_key', 'Venue', type_='unique')
    op.create_unique_constraint(None, 'Venue', ['website_link'])
    op.drop_column('Venue', 'website')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('website', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'Venue', type_='unique')
    op.create_unique_constraint('Venue_website_key', 'Venue', ['website'])
    op.drop_column('Venue', 'website_link')
    op.add_column('Artist', sa.Column('website', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Artist', type_='unique')
    op.create_unique_constraint('Artist_website_key', 'Artist', ['website'])
    op.drop_column('Artist', 'website_link')
    # ### end Alembic commands ###
