"""reverted description column names after looking at forms.py

Revision ID: 9979593c7025
Revises: c05db741b7eb
Create Date: 2022-05-27 21:18:15.143992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9979593c7025'
down_revision = 'c05db741b7eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('seeking_description', sa.String(), nullable=True))
    op.drop_column('Artist', 'seeking_venue_description')
    op.add_column('Venue', sa.Column('seeking_description', sa.String(), nullable=True))
    op.drop_column('Venue', 'seeking_talent_description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('seeking_talent_description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('Venue', 'seeking_description')
    op.add_column('Artist', sa.Column('seeking_venue_description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('Artist', 'seeking_description')
    # ### end Alembic commands ###
